# Generated by Django 5.2.8 on 2026-02-18 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="credit_score",
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name="CreditDeductionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deduction_points", models.IntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("not_received", "未收到货物"),
                            ("description_mismatch", "商品与描述不符"),
                            ("poor_service", "服务态度差"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "appeal_status",
                    models.CharField(
                        choices=[
                            ("pending", "待申诉"),
                            ("submitted", "已申诉"),
                            ("resolved", "已处理"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("appeal_content", models.TextField(blank=True)),
                ("appeal_response", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_deductions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
