# Generated by Django 4.2.7 on 2026-02-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_credit_score_creditdeductionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_card_photo',
            field=models.ImageField(upload_to='student_cards/', verbose_name='学生证照片'),
        ),
    ]
