# Generated by Django 5.2.8 on 2026-03-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_make_student_card_photo_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="student_id",
            field=models.CharField(
                blank=True,
                error_messages={"unique": "该学号已注册"},
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
