# Generated by Django 4.2.7 on 2025-11-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishitem",
            name="reject_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wishitem",
            name="status",
            field=models.CharField(
                choices=[("pending", "待审核"), ("approved", "已通过"), ("rejected", "被拒绝")],
                default="pending",
                max_length=10,
            ),
        ),
    ]
