# Generated by Django 5.2.8 on 2026-02-20 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_chatmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "received_item",
                    models.CharField(
                        choices=[("yes", "是"), ("no", "否")],
                        max_length=3,
                        verbose_name="是否收到货",
                    ),
                ),
                (
                    "description_match",
                    models.CharField(
                        choices=[("yes", "是"), ("no", "否")],
                        max_length=3,
                        verbose_name="是否与商品描述一致",
                    ),
                ),
                (
                    "service_attitude",
                    models.CharField(
                        choices=[("yes", "是"), ("no", "否")],
                        max_length=3,
                        verbose_name="商家服务态度",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="products.product",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("product", "buyer")},
            },
        ),
    ]
