# Generated by Django 5.2.8 on 2026-02-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_productevaluation"),
    ]

    operations = [
        migrations.AddField(
            model_name="productevaluation",
            name="evidence_photos",
            field=models.JSONField(blank=True, default=list, verbose_name="评价证据照片"),
        ),
    ]
