# Generated by Django 5.2.8 on 2026-02-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_productevaluation_evidence_photos"),
    ]

    operations = [
        migrations.AddField(
            model_name="productevaluation",
            name="appeal_content",
            field=models.TextField(blank=True, verbose_name="申诉内容"),
        ),
        migrations.AddField(
            model_name="productevaluation",
            name="appeal_deadline",
            field=models.DateTimeField(blank=True, null=True, verbose_name="申诉截止时间"),
        ),
        migrations.AddField(
            model_name="productevaluation",
            name="appeal_response",
            field=models.TextField(blank=True, verbose_name="申诉回复"),
        ),
        migrations.AddField(
            model_name="productevaluation",
            name="appeal_status",
            field=models.CharField(
                choices=[("pending", "待申诉"), ("submitted", "已申诉"), ("resolved", "已处理")],
                default="pending",
                max_length=10,
                verbose_name="申诉状态",
            ),
        ),
    ]
