# Generated by Django 5.2.8 on 2026-02-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_productevaluation_appeal_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productevaluation",
            name="appeal_evidence_photos",
            field=models.JSONField(blank=True, default=list, verbose_name="申诉证据照片"),
        ),
    ]
