# Generated by Django 5.2.8 on 2026-02-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_productevaluation_appeal_evidence_photos"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="inventory",
            field=models.PositiveIntegerField(default=1, verbose_name="库存数量"),
        ),
    ]
