# Generated by Django 5.2.8 on 2026-02-22 15:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_purchasehistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="purchasehistory",
            unique_together={("product", "buyer")},
        ),
    ]
