# Generated by Django 4.2.7 on 2026-02-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_purchasehistory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(
                choices=[
                    ('new', '全新'),
                    ('nine', '九成新'),
                    ('eight', '八成新'),
                    ('seven', '七成新'),
                    ('below_six', '六成新及以下')
                ],
                default='new',
                max_length=20,
                verbose_name='新旧程度'
            ),
        ),
    ]
