# Generated by Django 5.2.8 on 2026-03-02 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_add_condition_field"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="purchasehistory",
            unique_together=set(),
        ),
    ]
